### ISSUE TITLE
Unexpected token . when importing Library 

### ISSUE THREAD

**Issue by AudioSundae** [nick-michael/react-scrubber#1]
Whenever we `import { Scrubber } from 'react-scrubber'', I'm getting a

Unexpected token . in the console log.

Uncaught SyntaxError: Unexpected token .
    at new Script (vm.js:74)
    at createScript (vm.js:246)
    at Object.runInThisContext (vm.js:298)
    at Module._compile (internal/modules/cjs/loader.js:678)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722)
    at Module.load (internal/modules/cjs/loader.js:620)
    at tryModuleLoad (internal/modules/cjs/loader.js:559)
    at Function.Module._load (internal/modules/cjs/loader.js:551)
    at Module.require (internal/modules/cjs/loader.js:658)
    at require (internal/modules/cjs/helpers.js:20)

I'm importing it in my https://github.com/electron-react-boilerplate/electron-react-boilerplate project.

Thanks.

**Comment by AudioSundae** [comment]
@nick-michael looks like the require("./scrubber.css"); at line 39 is causing the issue for electron .

**Comment by nick-michael** [comment]
Thanks for raising, I'll try and take a look into it. I have had the scrubber running in an electron app so it's a bit of a strange one

**Comment by nick-michael** [comment]
Which css loader are you using in your project? Is it possible that the css-loader is not checking node_modules?

**Comment by nick-michael** [comment]
I was looking at your webpack config for that project:
```
{
        test: /^((?!\.global).)*\.css$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1,
              localIdentName: '[name]__[local]__[hash:base64:5]'
            }
          }
        ]
      }
```

I'm not too sure how css modules will work, but is it possible that because the react component is expecting to import a normal css file, maybe the css modules are causing issues?

I've notice the loader above doesn't use css modules but expects the file to be called `*.global.css` - I've never seen this convention before but I did a search online and it seems like this is the standard for Gatsby. I get the feeling the issue you're seeing is due to the fact that webpack is trying to load the css file as a css module instead of a standard css file

**Comment by AudioSundae** [comment]
@nick-michael Yes! It looks like it is trying to load the file as a module instead of the standard CSS file. Anytime we remove the require("./scrubber.css") line, it works well.

**Comment by nick-michael** [comment]
I think you might need to just add an exception to your webpack config for this, it's a bit odd to assume that every `.css` import will be using css modules. Maybe just modify your webpack config so that the `gloabal.css` regex test looks like this instead: `^((?!(\.global)|(react-scrubber)).)*\.css` - this should just exclude react scrubber from the css modules matcher and then change the standard css matcher to include it: `\.global\.css$|react-scrubber`

**Comment by AudioSundae** [comment]
Thanks Nick
